_BASE_: Base-PointRend-RCNN-FPN.yaml
MODEL:
  WEIGHTS: /home/shengdewu/workspace/facebookresearch/detectron2/myoutput/model_res101.pth #detectron2://ImageNetPretrained/MSRA/R-101.pkl
  MASK_ON: true
  RESNETS:
    DEPTH: 101

SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.002
  BIAS_LR_FACTOR: 0.8
  MAX_ITER: 2000
  STEPS : (1000, 1500)
DATASETS:
  TRAIN: ("coco_2014_train",)
  TEST: ("coco_2014_val",)

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704)
  MAX_SIZE_TRAIN: 800

  # `True` if cropping is used for data augmentation during training
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.7, 0.7]
    PROB: 1.0
  BRIGHT:
    ENABLED: True
    MIN: 0.5
    MAX: 1.6

  CONTRAST:
    ENABLED: True
    MIN: 0.5
    MAX: 1.6

  SATURATION:
    ENABLED: True
    MIN: 0.3
    MAX: 2.0

  COLOR:
    ENABLED: True

  RANDOM_FLIP:
    ENABLED: True
    PROB: 0.5
    HORIZONTAL: True
    VERTICAL: False
