_BASE_: "Base-SOLOv2.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  DEVICE: "cpu"
SOLVER:
  IMS_PER_BATCH: 1
  STEPS: (210000, 250000)
  MAX_ITER: 270000

DATALOADER:
  NUM_WORKERS: 1

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736)
  MAX_SIZE_TRAIN: 800

  HFLIP_TRAIN: False

  # `True` if cropping is used for data augmentation during training
  CROP:
    ENABLED: True
    # Cropping type. See documentation of `detectron2.data.transforms.RandomCrop` for explanation.
    TYPE: "relative_range"
    # Size of crop in range (0, 1] if CROP.TYPE is "relative" or "relative_range" and in number of
    # pixels if CROP.TYPE is "absolute"
    SIZE: [0.7, 0.7]
  # `True` if cropping is used for data augmentation during training
  BRIGHT:
    ENABLED: True
    MIN: 0.5
    MAX: 1.6

  CONTRAST:
    ENABLED: True
    MIN: 0.5
    MAX: 1.6

  SATURATION:
    ENABLED: True
    MIN: 0.3
    MAX: 2.0

  COLOR:
    ENABLED: True

