_BASE_: "Base-SOLOv2.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  DEVICE: "cpu"
SOLVER:
  IMS_PER_BATCH: 1
  STEPS: (210000, 250000)
  MAX_ITER: 270000

DATALOADER:
  NUM_WORKERS: 1
  ASPECT_RATIO_GROUPING: False

DATASETS:
  TRAIN: ("coco_2014_train",)
  TEST: ("coco_2014_val",)

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736)
  MAX_SIZE_TRAIN: 800

  # `True` if cropping is used for data augmentation during training
  CROP:
    ENABLED: True
    SIZE: [0.7, 0.7]
    PROB: 0.5
  BRIGHT:
    ENABLED: True
    MIN: 0.5
    MAX: 1.6

  CONTRAST:
    ENABLED: True
    MIN: 0.5
    MAX: 1.6

  SATURATION:
    ENABLED: False
    MIN: 0.3
    MAX: 2.0

  COLOR:
    ENABLED: True

  RANDOM_FLIP:
    ENABLED: True
    PROB: 0.5
    HORIZONTAL: True
    VERTICAL: False



